mandatoryAccounts:
  - name: Management
    description: The management (primary) account
    email: leectan+govcloud@amazon.com
    organizationalUnit: Root
  - name: LogArchive
    description: The log archive account
    email: leectan+govcloud-logarchive@amazon.com
    organizationalUnit: Security
  - name: Audit
    description: The security audit account
    email: leectan+govcloud-audit@amazon.com
    organizationalUnit: Security
accountIds:
  - email: leectan+govcloud@amazon.com
    accountId: "435520283566"
workloadAccounts: []
