mandatoryAccounts:
  - name: Management
    description: The management (primary) account
    email: leectan+govcloud@amazon.com
    organizationalUnit: Root
  - name: LogArchive
    description: The log archive account (same as Management in single-account mode)
    email: leectan+govcloud@amazon.com
    organizationalUnit: Root
  - name: Audit
    description: The security audit account (same as Management in single-account mode)
    email: leectan+govcloud@amazon.com
    organizationalUnit: Root
accountIds:
  - email: leectan+govcloud@amazon.com
    accountId: "435520283566"
workloadAccounts: []
